// Compile-time data preparation. Generates two files into `$OUT_DIR`, both
// `include!`d by `src/data.rs`:
//
//   synth_examples_gen.rs  -- a sorted static array mapping each member id to
//                             the verbatim text of its compiler-verified
//                             `SynthOOP_*.4dm` example file (via `include_str!`).
//   idf_gen.rs             -- the precomputed `ln(N / df)` IDF table, derived
//                             from the vendored `oop_corpus_stats.json`
//                             document frequencies.
//
// Doing both here keeps the final binary fully self-contained (no runtime file
// access) and keeps `ln()` out of the hot index-build path.
//
// IMPORTANT: synthetic example files are joined to members by `member_id` from
// the manifest, never by file name. `SynthOOP_<id>` names are lossy: `.` and
// `:` are replaced and the name is truncated to 4D's 31-character method-name
// limit with a hash suffix, so two distinct members can produce similar names
// and the name cannot be reversed back into an id.
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set by cargo");
    gen_synth_examples(&out_dir);
    gen_idf_table(&out_dir);
}

fn gen_synth_examples(out_dir: &str) {
    let manifest_path = "data/vendor/oop_synth_manifest.json";
    println!("cargo:rerun-if-changed={manifest_path}");
    println!("cargo:rerun-if-changed=data/vendor/methods");

    let manifest_text = fs::read_to_string(manifest_path)
        .unwrap_or_else(|e| panic!("failed to read {manifest_path}: {e}"));
    let manifest: serde_json::Value = serde_json::from_str(&manifest_text)
        .unwrap_or_else(|e| panic!("failed to parse {manifest_path}: {e}"));

    let files = manifest["files"]
        .as_object()
        .expect("oop_synth_manifest.json missing top-level `files` object");

    let methods_dir = Path::new("data/vendor/methods");
    // BTreeMap sorts by member id so the generated array (and therefore the
    // build output) is deterministic across runs/machines.
    let mut entries: BTreeMap<String, String> = BTreeMap::new();

    for (rel_path, meta) in files {
        let member_id = meta["member_id"]
            .as_str()
            .unwrap_or_else(|| panic!("manifest entry {rel_path} missing member_id"));
        // rel_path looks like "Sources/Methods/SynthOOP_<Name>.4dm"; the
        // vendored copy lives flattened under data/vendor/methods/ under the
        // same file name.
        let file_name = Path::new(rel_path)
            .file_name()
            .unwrap_or_else(|| panic!("unexpected manifest rel_path shape: {rel_path}"))
            .to_str()
            .expect("non-utf8 manifest path");
        let full_path = methods_dir.join(file_name);
        if !full_path.exists() {
            panic!(
                "vendored synth example file missing: {} (referenced by manifest entry {rel_path} for member {member_id})",
                full_path.display()
            );
        }
        let abs = fs::canonicalize(&full_path)
            .unwrap_or_else(|e| panic!("failed to canonicalize {}: {e}", full_path.display()));
        let abs_str = abs
            .to_str()
            .unwrap_or_else(|| panic!("non-utf8 path: {}", abs.display()))
            .to_string();
        if let Some(prev) = entries.insert(member_id.to_string(), abs_str) {
            panic!("duplicate synth example for member {member_id} (previous path: {prev})");
        }
    }

    let target_ids = manifest["target_ids"]
        .as_array()
        .expect("oop_synth_manifest.json missing top-level `target_ids` array");
    if target_ids.len() != entries.len() {
        panic!(
            "manifest declares {} target_ids but {} distinct member ids were resolved from `files`",
            target_ids.len(),
            entries.len()
        );
    }

    let mut code = String::new();
    code.push_str(
        "/// Generated by build.rs: (member id, verbatim compiler-verified .4dm example text).\n",
    );
    code.push_str("pub static SYNTH_EXAMPLES: &[(&str, &str)] = &[\n");
    for (member_id, abs_path) in &entries {
        code.push_str(&format!(
            "    ({member_id:?}, include_str!({abs_path:?})),\n"
        ));
    }
    code.push_str("];\n");

    let dest = Path::new(out_dir).join("synth_examples_gen.rs");
    fs::write(&dest, code).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}

fn gen_idf_table(out_dir: &str) {
    let stats_path = "data/vendor/oop_corpus_stats.json";
    println!("cargo:rerun-if-changed={stats_path}");

    let text = fs::read_to_string(stats_path)
        .unwrap_or_else(|e| panic!("failed to read {stats_path}: {e}"));
    let stats: serde_json::Value =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse {stats_path}: {e}"));

    let n = stats["corpus"]["members"]
        .as_u64()
        .expect("oop_corpus_stats.json missing corpus.members") as f64;
    if n < 1.0 {
        panic!("oop_corpus_stats.json reports a corpus of {n} members");
    }

    // `combined` is the union document frequency across the id, name, summary
    // and paramNames fields -- i.e. "in how many of the N members does this
    // token appear anywhere". That is exactly the denominator a query-token
    // IDF wants, since a query token may land in any of those fields.
    let df = stats["documentFrequency"]["combined"]
        .as_object()
        .expect("oop_corpus_stats.json missing documentFrequency.combined");

    // BTreeMap for a deterministic, binary-searchable generated table.
    let mut idf: BTreeMap<String, f64> = BTreeMap::new();
    for (token, count) in df {
        let d = count
            .as_u64()
            .unwrap_or_else(|| panic!("documentFrequency.combined[{token}] is not an integer"))
            as f64;
        if d <= 0.0 {
            panic!("documentFrequency.combined[{token}] is {d}, expected >= 1");
        }
        // ln(N / df): 0.0 for a token present in every member (e.g. "the",
        // df 502), rising as the token gets rarer. This is what replaces a
        // hand-written domain stopword list -- see src/index.rs.
        idf.insert(token.clone(), (n / d).ln());
    }

    let mut code = String::new();
    code.push_str(&format!(
        "/// Generated by build.rs from data/vendor/oop_corpus_stats.json.\n\
         /// Corpus size N used for `ln(N / df)`.\n\
         pub const CORPUS_MEMBERS: f32 = {n:.1};\n"
    ));
    code.push_str(
        "/// (token, ln(N / df)) sorted by token, for binary search at index-build time.\n",
    );
    code.push_str("pub static IDF_TABLE: &[(&str, f32)] = &[\n");
    for (token, value) in &idf {
        code.push_str(&format!("    ({token:?}, {value:?}f32),\n"));
    }
    code.push_str("];\n");

    let dest = Path::new(out_dir).join("idf_gen.rs");
    fs::write(&dest, code).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
