//! Build-time embedded data. Everything here is baked into the binary at
//! compile time — no file or network access is performed at runtime.

/// The pinned `4d-static-docs` OOP IR (see `data/vendor/COMMIT` for
/// provenance: repo, commit sha, and fetch date).
pub static IR_JSON: &str = include_str!("../data/vendor/4d-oop-ir.json");

/// Hand-written documentation examples harvested from the 4D docs, with
/// per-block compiler-verification provenance.
pub static DOC_EXAMPLES_JSON: &str = include_str!("../data/vendor/oop_doc_examples.json");

/// Per-member index into the synthetic example corpus (which file, and which
/// overload/variant blocks live at which line ranges inside it).
pub static SYNTH_MANIFEST_JSON: &str = include_str!("../data/vendor/oop_synth_manifest.json");

/// Hand-curated deterministic colloquial/synonym expansion table used by the
/// tokenizer (see `index.rs`).
pub static ALIASES_JSON: &str = include_str!("../data/aliases.json");

// Generated by build.rs from data/vendor/oop_synth_manifest.json +
// data/vendor/methods/*.4dm: `pub static SYNTH_EXAMPLES: &[(&str, &str)]`,
// mapping each member id to the verbatim text of its compiler-verified
// synthetic example file.
include!(concat!(env!("OUT_DIR"), "/synth_examples_gen.rs"));

// Generated by build.rs from data/vendor/oop_corpus_stats.json:
// `pub const CORPUS_MEMBERS: f32` and `pub static IDF_TABLE: &[(&str, f32)]`,
// the precomputed `ln(N / df)` table used by the scorer.
include!(concat!(env!("OUT_DIR"), "/idf_gen.rs"));

/// `ln(N / df)` for `token`, or `None` if the token does not appear anywhere
/// in the corpus's id/name/summary/paramNames fields.
pub fn idf(token: &str) -> Option<f32> {
    IDF_TABLE
        .binary_search_by(|(t, _)| (*t).cmp(token))
        .ok()
        .map(|i| IDF_TABLE[i].1)
}
